// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: 'http://localhost:8000' | (string & {})
}

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>
}

/**
 * ModelInfo
 *
 * Information about an available STT model.
 */
export type ModelInfo = {
  /**
   * Id
   */
  id: string
  /**
   * Name
   */
  name: string
  /**
   * Description
   */
  description: string
  /**
   * Workflow Type
   */
  workflow_type?: 'streaming' | 'buffered'
  /**
   * Expected Latency Ms
   */
  expected_latency_ms?: [number, number]
}

/**
 * ModelStatus
 *
 * Current status of the model system.
 */
export type ModelStatus = {
  /**
   * Current Model
   */
  current_model?: string | null
  /**
   * Is Loaded
   */
  is_loaded: boolean
  /**
   * Status
   */
  status: string
}

/**
 * ModerationConfig
 *
 * Configuration for content moderation feature.
 */
export type ModerationConfig = {
  /**
   * Default Enabled
   *
   * Whether moderation is enabled by default
   */
  default_enabled: boolean
  /**
   * Confidence Threshold
   *
   * Minimum confidence to consider a result valid
   */
  confidence_threshold: number
  /**
   * On Final Only
   *
   * Only run moderation on is_final=True results
   */
  on_final_only: boolean
}

/**
 * ModerationStatus
 *
 * Current status of content moderation feature.
 *
 * Now uses unified span detector (ViSoBERT-HSD-Span) for both
 * span detection and label inference.
 */
export type ModerationStatus = {
  /**
   * Enabled
   *
   * Whether content moderation is currently enabled
   */
  enabled: boolean
  /**
   * Span Detector Active
   *
   * Whether the span detector model is loaded and ready
   */
  span_detector_active?: boolean
  config: ModerationConfig
}

/**
 * ModerationToggleResponse
 *
 * Response for moderation toggle operation.
 */
export type ModerationToggleResponse = {
  /**
   * Enabled
   */
  enabled: boolean
  /**
   * Span Detector Active
   */
  span_detector_active?: boolean
}

/**
 * SwitchModelResponse
 *
 * Response for model switch operation.
 */
export type SwitchModelResponse = {
  /**
   * Status
   */
  status: string
  /**
   * Current Model
   */
  current_model: string
}

/**
 * TranscriptionLog
 *
 * Database model for storing transcription history.
 *
 * Each record represents a transcription session (one recording session).
 * Includes moderation data (label, detected keywords, etc.) when content moderation is enabled.
 */
export type TranscriptionLog = {
  /**
   * Id
   */
  id?: number | null
  /**
   * Session Id
   *
   * Unique session identifier
   */
  session_id: string
  /**
   * Model Id
   *
   * Model used for transcription
   */
  model_id: string
  /**
   * Content
   *
   * Transcribed text content
   */
  content: string
  /**
   * Latency Ms
   *
   * Processing latency in milliseconds
   */
  latency_ms?: number
  /**
   * Created At
   *
   * Timestamp of creation
   */
  created_at?: string
  /**
   * Moderation Label
   *
   * Moderation label: CLEAN, OFFENSIVE, or HATE
   */
  moderation_label?: string | null
  /**
   * Moderation Confidence
   *
   * Confidence score of moderation (0.0 to 1.0)
   */
  moderation_confidence?: number | null
  /**
   * Is Flagged
   *
   * Whether the content was flagged by moderation
   */
  is_flagged?: boolean | null
  /**
   * Detected Keywords
   *
   * List of detected bad/offensive keywords in the text
   */
  detected_keywords?: Array<string> | null
}

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>
  /**
   * Message
   */
  msg: string
  /**
   * Error Type
   */
  type: string
}

export type RootData = {
  body?: never
  path?: never
  query?: never
  url: '/'
}

export type RootResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type HealthCheckData = {
  body?: never
  path?: never
  query?: never
  url: '/health'
}

export type HealthCheckResponses = {
  /**
   * Successful Response
   */
  200: unknown
}

export type GetModelsData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/models'
}

export type GetModelsResponses = {
  /**
   * Response Get Models Api V1 Models Get
   *
   * Successful Response
   */
  200: Array<ModelInfo>
}

export type GetModelsResponse = GetModelsResponses[keyof GetModelsResponses]

export type GetHistoryData = {
  body?: never
  path?: never
  query?: {
    /**
     * Page
     */
    page?: number
    /**
     * Limit
     */
    limit?: number
    /**
     * Search
     */
    search?: string
    /**
     * Model
     */
    model?: string
    /**
     * Min Latency
     */
    min_latency?: number
    /**
     * Max Latency
     */
    max_latency?: number
    /**
     * Start Date
     */
    start_date?: string
    /**
     * End Date
     */
    end_date?: string
  }
  url: '/api/v1/history'
}

export type GetHistoryErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type GetHistoryError = GetHistoryErrors[keyof GetHistoryErrors]

export type GetHistoryResponses = {
  /**
   * Response Get History Api V1 History Get
   *
   * Successful Response
   */
  200: Array<TranscriptionLog>
}

export type GetHistoryResponse = GetHistoryResponses[keyof GetHistoryResponses]

export type SwitchModelData = {
  body?: never
  path?: never
  query: {
    /**
     * Model
     */
    model: string
  }
  url: '/api/v1/models/switch'
}

export type SwitchModelErrors = {
  /**
   * Invalid model name
   */
  400: unknown
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type SwitchModelError = SwitchModelErrors[keyof SwitchModelErrors]

export type SwitchModelResponses = {
  /**
   * Successful Response
   */
  200: SwitchModelResponse
}

export type SwitchModelResponse2 =
  SwitchModelResponses[keyof SwitchModelResponses]

export type GetModelStatusData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/models/status'
}

export type GetModelStatusResponses = {
  /**
   * Successful Response
   */
  200: ModelStatus
}

export type GetModelStatusResponse =
  GetModelStatusResponses[keyof GetModelStatusResponses]

export type GetModerationStatusData = {
  body?: never
  path?: never
  query?: never
  url: '/api/v1/moderation/status'
}

export type GetModerationStatusResponses = {
  /**
   * Successful Response
   */
  200: ModerationStatus
}

export type GetModerationStatusResponse =
  GetModerationStatusResponses[keyof GetModerationStatusResponses]

export type ToggleModerationData = {
  body?: never
  path?: never
  query?: {
    /**
     * Enabled
     */
    enabled?: boolean
  }
  url: '/api/v1/moderation/toggle'
}

export type ToggleModerationErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError
}

export type ToggleModerationError =
  ToggleModerationErrors[keyof ToggleModerationErrors]

export type ToggleModerationResponses = {
  /**
   * Successful Response
   */
  200: ModerationToggleResponse
}

export type ToggleModerationResponse =
  ToggleModerationResponses[keyof ToggleModerationResponses]
