// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod'

/**
 * ModelInfo
 *
 * Information about an available STT model.
 */
export const zModelInfo = z.object({
  id: z.string(),
  name: z.string(),
  description: z.string(),
  workflow_type: z.optional(z.enum(['streaming', 'buffered'])),
  expected_latency_ms: z
    .optional(z.tuple([z.int(), z.int()]))
    .default([100, 500]),
})

/**
 * ModelStatus
 *
 * Current status of the model system.
 */
export const zModelStatus = z.object({
  current_model: z.optional(z.union([z.string(), z.null()])),
  is_loaded: z.boolean(),
  status: z.string(),
})

/**
 * ModerationConfig
 *
 * Configuration for content moderation feature.
 */
export const zModerationConfig = z.object({
  default_enabled: z.boolean(),
  confidence_threshold: z.number().gte(0).lte(1),
  on_final_only: z.boolean(),
})

/**
 * ModerationStatus
 *
 * Current status of content moderation feature.
 *
 * Now uses unified span detector (ViSoBERT-HSD-Span) for both
 * span detection and label inference.
 */
export const zModerationStatus = z.object({
  enabled: z.boolean(),
  span_detector_active: z.optional(z.boolean()).default(false),
  config: zModerationConfig,
})

/**
 * ModerationToggleResponse
 *
 * Response for moderation toggle operation.
 */
export const zModerationToggleResponse = z.object({
  enabled: z.boolean(),
  span_detector_active: z.optional(z.boolean()).default(false),
})

/**
 * SwitchModelResponse
 *
 * Response for model switch operation.
 */
export const zSwitchModelResponse = z.object({
  status: z.string(),
  current_model: z.string(),
})

/**
 * TranscriptionLog
 *
 * Database model for storing transcription history.
 *
 * Each record represents a transcription session (one recording session).
 * Includes moderation data (label, detected keywords, etc.) when content moderation is enabled.
 */
export const zTranscriptionLog = z.object({
  id: z.optional(z.union([z.int(), z.null()])),
  session_id: z.string(),
  model_id: z.string(),
  content: z.string(),
  latency_ms: z.optional(z.number()).default(0),
  created_at: z.optional(z.string()),
  moderation_label: z.optional(z.union([z.string(), z.null()])),
  moderation_confidence: z.optional(z.union([z.number(), z.null()])),
  is_flagged: z.optional(z.union([z.boolean(), z.null()])),
  detected_keywords: z.optional(z.union([z.array(z.string()), z.null()])),
})

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
})

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
})

export const zRootData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zHealthCheckData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

export const zGetModelsData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Response Get Models Api V1 Models Get
 *
 * Successful Response
 */
export const zGetModelsResponse = z.array(zModelInfo)

export const zGetHistoryData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      page: z.optional(z.int()).default(1),
      limit: z.optional(z.int()).default(50),
      search: z.optional(z.string()),
      model: z.optional(z.string()),
      min_latency: z.optional(z.number()),
      max_latency: z.optional(z.number()),
      start_date: z.optional(z.iso.datetime()),
      end_date: z.optional(z.iso.datetime()),
    }),
  ),
})

/**
 * Response Get History Api V1 History Get
 *
 * Successful Response
 */
export const zGetHistoryResponse = z.array(zTranscriptionLog)

export const zSwitchModelData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    model: z.string(),
  }),
})

/**
 * Successful Response
 */
export const zSwitchModelResponse2 = zSwitchModelResponse

export const zGetModelStatusData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zGetModelStatusResponse = zModelStatus

export const zGetModerationStatusData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
})

/**
 * Successful Response
 */
export const zGetModerationStatusResponse = zModerationStatus

export const zToggleModerationData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      enabled: z.optional(z.boolean()).default(true),
    }),
  ),
})

/**
 * Successful Response
 */
export const zToggleModerationResponse = zModerationToggleResponse
